class GameContent {
  static const Map<int, String> games = {
    1: "Everyone drinks",
    2: "Waterfall",
    3: "Never have I ever",
    4: "Truth round",
    5: "Accent challenge",
    6: "Dance battle",
    7: "Compliment circle",
    8: "Thumb master",
    9: "Rhyme game",
    10: "Impersonation round",
    11: "Silent round",
    12: "Categories",
    13: "Rock paper scissors tournament",
    14: "Speed round",
    15: "Memory game",
    16: "Two truths and a lie",
    17: "Charades",
    18: "Story builder",
    19: "Staring contest",
    20: "Send a text to the last person you talked to",
  };

  static const Map<int, String> challenges = {
    1: "Do 10 pushups",
    2: "Sing a song",
    3: "Speak in accents for 2 rounds",
    4: "No using hands for 1 round",
    5: "Act like a cat",
    6: "Let someone post on your story",
    7: "Dance without music",
    8: "Whisper for 2 rounds",
    9: "Trade clothes item",
    10: "Imitate someone here",
    11: "Speak only questions",
    12: "Freeze randomly",
    13: "Talk backwards",
    14: "Laugh every sentence",
    15: "Wear socks on hands",
    16: "Do a runway walk",
    17: "Act drunk (ironically)",
    18: "Compliment everyone",
    19: "No blinking challenge",
    20: "Call someone and sing to them",
  };
}
